services:
  api:
    build: .
    container_name: monitor-api

    ports:
      - "8000:8000"

    volumes:
      - .:/app

    depends_on:
      - db

    environment:
      DATABASE_URL: postgresql://monitor_user:monitor_password@db:5432/monitor_db

  db:
    image: postgres:17

    container_name: monitor-db

    environment:
      POSTGRES_USER: monitor_user
      POSTGRES_PASSWORD: monitor_password
      POSTGRES_DB: monitor_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: